### ISSUE TITLE
error - doesn't run

### ISSUE THREAD

**Issue by adrian-rt** [agrawalsmart7/scodescanner#4]
Hi,

this is what I get when running  python3 scscanner.py 
```

Traceback (most recent call last):
  File "scscanner.py", line 3, in <module>
    from helper import yaml_main, php_main
  File "/home/adrian/Downloads/tools/scodescanner/helper.py", line 10, in <module>
    from src.common.file_sender import jira_issue_creater, slack_issue_creator
ModuleNotFoundError: No module named 'src.common'

```

**Comment by agrawalsmart7** [comment]
Hi, Thanks for opening the issue, There was one file missing which I just added. Can you please try again and let me know if you found any issue.

**Comment by adrian-rt** [comment]
works now, thanks.

**Comment by Hndreamer** [comment]
hello,there is a trouble when i  running python3 scscanner.py
Traceback (most recent call last):
  File "/root/桌面/scodescanner/scscanner.py", line 3, in <module>
    from helper import yaml_main, php_main
  File "/root/桌面/scodescanner/helper.py", line 69, in <module>
    sys.path.append(str(os.getcwd)+"/src/")
NameError: name 'sys' is not defined

**Comment by agrawalsmart7** [comment]
You need to import that library.

Try to add this line - import sys - Where all the libraries are imported

**Comment by lutong9527** [comment]
ImportError: cannot import name 'final'
这个怎么解决？谢谢
