### ISSUE TITLE
Module not found - No module named 'src.php'

### ISSUE THREAD

**Issue by banner-prog** [agrawalsmart7/scodescanner#5]
I am getting an error when running the command `python3 scscanner.py --help`

```
Traceback (most recent call last):
  File "/home/corrupted/scodescanner/scscanner.py", line 3, in <module>
    from helper import yaml_main, php_main
  File "/home/corrupted/scodescanner/helper.py", line 4, in <module>
    from src.php.folder_parserer import folderparser, fileparser
ModuleNotFoundError: No module named 'src.php'
```

![image](https://user-images.githubusercontent.com/63605861/185172061-e55af1a5-6d9d-4af7-90b4-694303ad74f2.png)

**Comment by agrawalsmart7** [comment]
Hi Sorry for late,

I have changed the code, can you please check again.
