### ISSUE TITLE
error - doesn't run

### ISSUE THREAD

**Issue by svchost9913** [agrawalsmart7/scodescanner#6]
python scscanner.py  -h

Traceback (most recent call last):
  File "scscanner.py", line 3, in <module>
    from helper import yaml_main, php_main
  File "/root/scodescanner/helper.py", line 2, in <module>
    from typing import final
ImportError: cannot import name 'final' from 'typing' (/root/.pyenv/versions/3.7.13/lib/python3.7/typing.py)

**Comment by agrawalsmart7** [comment]
Hi I have removed the line, please try again. There is some importing issues.

**Comment by svchost9913** [comment]
python3 scscanner.py
Traceback (most recent call last):
  File "/root/tools/scodescanner/scscanner.py", line 3, in <module>
    from helper import yaml_main, php_main
  File "/root/tools/scodescanner/helper.py", line 69, in <module>
    sys.path.append(str(os.getcwd)+"/src/")
NameError: name 'sys' is not defined

It's been like this after a fresh install.
